name: OVMF Build

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    name: OVMF Build
    runs-on: ubuntu-22.04

    steps:
    - name: Install build Packages
      run: sudo apt-get install -qq --no-install-recommends uuid-dev iasl nasm
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup BaseTools
      run: |
        make -C BaseTools
    - name: Build
      run: |
        source edksetup.sh BaseTools
        build -a X64 -t GCC5 -b RELEASE -p OvmfPkg/OvmfPkgX64.dsc \
          -D FD_SIZE_2MB \
          -D NETWORK_ALLOW_HTTP_CONNECTIONS=false \
          -D NETWORK_ISCSI_ENABLE=false
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OVMF-files
        path: Build/OvmfX64/RELEASE_GCC5/FV/OVMF*.fd
